default: &default
  adapter: mysql2
  username: root
  database: tours
  password: 
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default  

test:
  <<: *default

production:
  <<: *default
  password: ''